# Generated by Django 2.2 on 2024-04-18 11:32

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stickerz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopper',
            name='billingAddress',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=512)),
        ),
        migrations.AlterField(
            model_name='shopper',
            name='billingCountry',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=64)),
        ),
        migrations.AlterField(
            model_name='shopper',
            name='billingFName',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=64)),
        ),
        migrations.AlterField(
            model_name='shopper',
            name='billingLName',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=64)),
        ),
        migrations.AlterField(
            model_name='shopper',
            name='billingPostcode',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=8)),
        ),
        migrations.AlterField(
            model_name='shopper',
            name='cardNo',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=16)),
        ),
        migrations.AlterField(
            model_name='shopper',
            name='cvv',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=3)),
        ),
        migrations.AlterField(
            model_name='shopper',
            name='expiration',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=4)),
        ),
        migrations.AlterField(
            model_name='shopper',
            name='shippingAddress',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=512)),
        ),
        migrations.AlterField(
            model_name='shopper',
            name='shippingCountry',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=64)),
        ),
        migrations.AlterField(
            model_name='shopper',
            name='shippingFName',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=64)),
        ),
        migrations.AlterField(
            model_name='shopper',
            name='shippingLName',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=64)),
        ),
        migrations.AlterField(
            model_name='shopper',
            name='shippingPostcode',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=8)),
        ),
    ]
